### ISSUE TITLE
$filter is not working

### ISSUE THREAD

**Issue by udiedrichsen** [cult-of-coders/grapher-live#6]
In your grapher live site:
http://grapher-live.cultofcoders.com/grapher

I hacked in the following query: 

```
{
    posts: {
        $filter({filters, params}) {
            filters.ownerId = params.ownerId
        },
        ownerId:1,
        title: 1
    }
}
```

as parameters:

```
{
    ownerId:"UNKNOWN"
}
```

To my surprise it shows all results from posts and not 0 results.

**Comment by theodorDiaconu** [comment]
solved.
