### ISSUE TITLE
Port to Vue?

### ISSUE THREAD

**Issue by Herteby** [cult-of-coders/grapher-live#9]
I was thinking I could port grapher-live to Vue maybe.
I don't know any React though, so translating the code wouldn't be very fun hehe.
Do you actually use grapher-live a lot in development? Or do you mostly have it as a demo?

**Comment by Herteby** [comment]
Hmm, or maybe it'd be better to find a way for Vue and React to live together. So that there aren't two versions of grapher-live to maintain.

**Comment by theodorDiaconu** [comment]
True that, I think we can now make use of lazy loading from meteor to load react , brace and others so it won't load your module

**Comment by Herteby** [comment]
@theodorDiaconu Woo, I got it working! It was actually not that difficult.
I  just had to make this Vue wrapper component:
```
<template>
  <div></div>
</template>

<script>
  export default {
    mounted(){
      Promise.all([import('react'),import('react-dom'),import('meteor/cultofcoders:grapher-live')])
      .then(([{default:React}, {default:ReactDOM}, {GrapherLive}]) => {
        ReactDOM.render(React.createElement(GrapherLive, null), this.$el)
      })
    },
    destroyed(){
      import('react-dom').then(({default:ReactDOM}) => {
        ReactDOM.unmountComponentAtNode(this.$el)
      })
    }
  }
</script>
```
Maybe you can put this in the docs somewhere :slightly_smiling_face:

**Comment by Herteby** [comment]
Or maybe I should include this in grapher-vue actually.

**Comment by theodorDiaconu** [comment]
@Herteby good job
